# Generated by Django 3.0.8 on 2020-08-05 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200805_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payments',
        ),
    ]
