# Generated by Django 3.0.8 on 2020-08-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200805_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
