# Generated by Django 3.0.8 on 2020-08-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200805_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_id',
            new_name='payment_intent_id',
        ),
    ]
