# Generated by Django 3.0.8 on 2020-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200805_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
