# Generated by Django 3.1 on 2020-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_payed',
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(),
        ),
    ]
