# Generated by Django 3.1 on 2020-08-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200808_2258'),
        ('booking', '0002_auto_20200809_1138'),
    ]

    operations = [
    ]
