# Generated by Django 3.0.8 on 2020-08-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='price',
            new_name='amount',
        ),
    ]
