# Generated by Django 3.1 on 2020-08-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200812_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='duration',
            field=models.DurationField(),
        ),
    ]
