# Generated by Django 3.0.8 on 2020-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200805_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
