# Generated by Django 3.0.8 on 2020-08-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200805_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
