# Generated by Django 3.1 on 2020-08-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200809_1138'),
        ('tours', '0004_auto_20200806_1144'),
    ]

    operations = [
    ]
