# Generated by Django 3.1 on 2020-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200812_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='limit_booking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
