# Generated by Django 3.0.8 on 2020-08-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
